# Generated by Django 3.1.4 on 2020-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20201202_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='doc_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
